# Generated by Django 5.1.5 on 2025-01-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clgcourses',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=10)),
                ('course_rank', models.IntegerField()),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='clgstudent',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('enrollment_date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'clgstudents',
            },
        ),
    ]
